language: python

python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pytest
  - pip install python-coveralls

script:
  - coverage run --source=overloading -m py.test
  - coverage report

after_success:
  - coveralls

cache:
  - pip
